-- DROP TABLE farms;
-- SELECT  * FROM farms LIMIT 0;

CREATE TABLE IF NOT EXISTS farms
(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    createdDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	modifiedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	active BIT DEFAULT 1
);