-- DROP TABLE queen_bees;
-- SELECT  * FROM queen_bees LIMIT 0;

CREATE TABLE IF NOT EXISTS queen_bees
(
	id INT PRIMARY KEY AUTO_INCREMENT,
    hive_id INT,
    mark_color VARCHAR(255) NOT NULL,
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	modified_date DATETIME ON UPDATE CURRENT_TIMESTAMP,
	active BIT DEFAULT 1
);