-- DROP TABLE queenBees;
-- SELECT  * FROM queenBees LIMIT 0;

CREATE TABLE IF NOT EXISTS queenBees
(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    hiveID INT,
    markColor VARCHAR(255) NOT NULL,
    createdDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	modifiedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	active BIT DEFAULT 1
);