web: java -jar target/*-jar-with-dependencies.jar
release: java -jar target/dependency/liquibase.jar --changeLogFile=src/main/sql/dbchangelog.xml --url=$JDBC_DATABASE_URL --classpath=target/dependency/jdbc_driver.jar update

