-- DROP TABLE roles;

CREATE TABLE IF NOT EXISTS roles
	( role_name VARCHAR(20) NOT NULL PRIMARY KEY
	);

INSERT INTO roles (role_name) VALUES ('user') ON CONFLICT DO NOTHING;

INSERT INTO roles (role_name) VALUES ('admin') ON CONFLICT DO NOTHING;
